theme: jekyll-theme-slate
title: HAI-GEN 2020
title_separator: "-"
description: Human-AI Co-Creation with Generative Models\nIUI 2020, Workshop, March 17, Cagliari, Italy
author:
  name: I do not know
