theme: jekyll-theme-slate
title: HAI-GEN 2020
title_separator: "-"
description: 1st Workshop on Human-AI Co-Creation with Generative Models, IUI 2020, Cagliari, Italy . Tuesday, March 17, 8:30 - 12:30
