theme: jekyll-theme-slate
title: HAI-GEN 2020
title_separator: "-"
name                     : &name "blablabla"
description: Human-AI Co-Creation with Generative Models         IUI 2020, Workshop, March 17, Cagliari, Italy

