theme: jekyll-theme-slate
title: HAI-GEN 2020
title_separator: "-"
description: 
Workshop on Human-AI Co-Creation with Generative Models, IUI 2020, Cagliari, Italy 
Tuesday, March 17, 8:30 AM - 12:30 PM
